### ISSUE TITLE
Add support for authentication event

### ISSUE THREAD

**Issue by remixz** [remixz/messenger-bot#1]
There's one type of event that I didn't implement that can be made to the webhook that's an "authentication" event. Looks like it happens when the user uses Facebook's "Send to Messenger" plugin: https://developers.facebook.com/docs/messenger-platform/implementation#send_to_messenger_plugin

The payload's format is here: https://developers.facebook.com/docs/messenger-platform/webhook-reference#auth Looks like it'd be pretty simple to detect, since it has some unique properties in its payload, so I'm going to make this a starter issue. I'm happy to help out if anyone runs into issues with this!

**Comment by maciekmm** [comment]
Given that it's the only event that has no guaranteed properties in the payload it can be detected in the process of elimination as I did here: https://github.com/maciekmm/messenger-platform-go-sdk/blob/master/messenger.go#L62-76

**Comment by hpincket** [comment]
Hi, I am trying to give this a shot, but I am confused. Does it have unique properties in it's payload? `optin.ref`, or is this property not guaranteed? Thanks for the project by the way.

**Comment by maciekmm** [comment]
I have just tested it. The _optin_ property is always there, if the postback data-ref attribute is not specified the _ref_ attribute is just empty:

`{"object":"page","entry":[{"id":510249619162304,"time":1461167227231,"messaging":[{"sender":{"id":1066835436691078},"recipient":{"id":510249619162304},"timestamp":1461167227231,"optin":{"ref":""}}]}]}`

>

**Comment by giladaya** [comment]
Any ETA on merging #6 ?

**Comment by maciekmm** [comment]
@giladaya,
@remixz  seems to be not online lately and I wanted to have his feedback, as myself I'm not a javascript dev.

On the other side I have been granted the power to push into the repository and I will merge the pull request. Thanks for reminding.
