### ISSUE TITLE
Serving an image

### ISSUE THREAD

**Issue by spwizard** [remixz/messenger-bot#10]
Hi,
I am trying to serve an image in a template but keep getting 
Error, wrong validation token
I've tried setting a static directory for serving images but that dosent seem to work either
Any help would be appreciated.

**Comment by maciekmm** [comment]
@spwizard  Could you provide us with code to reproduce?

It'd also be cool to get the full error stack if possible.

Thanks.

**Comment by spwizard** [comment]
Ive sent you an email

**Comment by maciekmm** [comment]
@spwizard 
I have not received any email unfortunately ;/

**Comment by spwizard** [comment]
Just resent

**Comment by maciekmm** [comment]
Not an issue with messenger-bot. @spwizard passed the bot's middleware to http.createServer instead of express so the images endpoint was never hit.
