### ISSUE TITLE
trigger specific message

### ISSUE THREAD

**Issue by yaminodestiny** [remixz/messenger-bot#14]
hi,

Would like to ask how i am set for like specific message?
For example, if the user post hi, the bot would reply how may i help you?
if the user post i have a question, the bot would reply something else?

Thanks

**Comment by maciekmm** [comment]
Take a look at: https://wit.ai/

**Comment by remixz** [comment]
@maciekmm 👍 

@yaminodestiny If you are looking to do this with this library, here's an example of how it could work:

```js
bot.on('message', (payload, reply) => {
  let text = payload.message.text

  if (text === 'hi') {
    reply({text: 'hello!')}
  }
})
```

However, that would only catch the literal text `hi`. You might want to use a RegExp instead to catch a multitude of values, like "hi", "hello", etc.

This library doesn't handle any sort of message state, i.e. where the user is in a conversation. For that, you'd probably want to use something like wit.ai, or [botkit](https://github.com/howdyai/botkit). botkit might fit your use case better if you're looking for message parsing and state handling. I don't have any personal experience with it, but I do know it's a well-made library. Good luck! 😄

**Comment by yaminodestiny** [comment]
Thanks man

**Comment by yaminodestiny** [comment]
@remixz Thanks
