### ISSUE TITLE
Combining with wit.ai

### ISSUE THREAD

**Issue by DVassilev** [remixz/messenger-bot#17]
Hello,

Any instructions on how to integrate wit.ai with this?

Thanks,
Daniel

**Comment by DVassilev** [comment]
@remixz ?

**Comment by eXeDK** [comment]
Have a look at https://www.npmjs.com/package/node-wit. Using that you should be able to do it quite easily

**Comment by eXeDK** [comment]
@DVassilev did you figure this out for us to close this issue?
