### ISSUE TITLE
How to get PAGE_TOKEN, VERIFY_TOKEN, APP_SECRET ?

### ISSUE THREAD

**Issue by anhphuong** [remixz/messenger-bot#19]
Dear Mr remixz,

Please show me how & where to take (get) value for PAGE_TOKEN, VERIFY_TOKEN, APP_SECRET!

Thanks

**Comment by andreasbhansen** [comment]
You'll find them all in your Facebook Developer app settings.

**Comment by mrbarletta** [comment]
Follow this guide  to know exactly how to find those values

[](https://developers.facebook.com/docs/messenger-platform/quickstart)

**Comment by eXeDK** [comment]
See https://developers.facebook.com/docs/messenger-platform/quickstart and https://developers.facebook.com/docs/messenger-platform/webhook-reference#setup
