### ISSUE TITLE
Structured Message Example

### ISSUE THREAD

**Issue by evancloutier** [remixz/messenger-bot#20]
Hey,

Does anyone have an example of how to send a structured message with this client?

Thanks,

Evan

**Comment by bernatfortet** [comment]
+1

**Comment by andreasbhansen** [comment]
Under "7. Send a Structured Message"
Link: https://developers.facebook.com/docs/messenger-platform/quickstart

You just need to send the ```attachment``` object.

**Comment by eXeDK** [comment]
@evancloutier did you find your answer?
