### ISSUE TITLE
Add support for Sender Actions

### ISSUE THREAD

**Issue by remixz** [remixz/messenger-bot#23]
Facebook recently added "Sender Actions" to the platform, which let you toggle a typing state for the bot. https://developers.facebook.com/docs/messenger-platform/send-api-reference/sender-actions

Since they're not part of the `message` object in a payload, this library currently doesn't support them. We should add them somehow, likely as something separate from `sendMessage` / `reply`.

The first solution I can think of is add toggling sender actions as a third param in the event handler. Something like `(event, reply, actions) => {}`, with `actions` having functions like `actions.setTyping(state: boolean, callback: function)` and `actions.markRead(callback: function)`. This would let adding actions not be a breaking change to the module, which would be nice.

**Comment by eXeDK** [comment]
I have taken I slightly different approach but like the idea. Maybe some of the code in my current pull request will be useful.
