### ISSUE TITLE
Add support for new webhook events

### ISSUE THREAD

**Issue by remixz** [remixz/messenger-bot#24]
Here are the ones we're missing now:

- [ ] https://developers.facebook.com/docs/messenger-platform/webhook-reference/account-linking
- [ ] https://developers.facebook.com/docs/messenger-platform/webhook-reference/message-read
- [ ] https://developers.facebook.com/docs/messenger-platform/webhook-reference/message-echo

Should be a pretty simple matter of just adding them to the `_handleMessage` function (https://github.com/remixz/messenger-bot/blob/master/index.js#L95), and then adding tests.

**Comment by remixz** [comment]
Actually, we already have basic support for the message echo event, as it'll be captured by our `message` event callback. However, because I think most people would rather not handle their own messages as incoming messages, I think we should create a new event by checking if the `is_echo` param is on the incoming payload, and then delegate based on that.

**Comment by eXeDK** [comment]
Have a look at the new pull request, should do this. Sadly I didn't see your issues before I wrote the code.
