### ISSUE TITLE
verify error

### ISSUE THREAD

**Issue by vinnitu** [remixz/messenger-bot#27]
I have digitalocean vps and try to place your code there.
But when I verify webhook (https://x.x.x.x:3000) get error

```
The URL couldn't be validated. Callback verification failed with the following errors: curl_errno = 35; curl_error = Unknown SSL protocol error in connection to x.x.x.x:3000 ; HTTP Status Code = 200; HTTP Message = Connection established
```
What i need to do?

**Comment by DVassilev** [comment]
@vinnitu Do you have SSL set up? Based on the error that may be the issue.
