### ISSUE TITLE
Use fb-messenger?

### ISSUE THREAD

**Issue by DiegoRBaquero** [remixz/messenger-bot#3]
Hi there! I found this cool project and wanted to share mine, maybe you find it useful and use it as a module in yours :)

Link: https://github.com/DiegoRBaquero/node-fb-messenger 
NPM module: https://www.npmjs.com/package/fb-messenger

Thank you for your time :)

**Comment by maciekmm** [comment]
Hello @DiegoRBaquero,
Thanks for suggestions, but as you can see we have majority implemented and test covered already.

Good luck!
