### ISSUE TITLE
Message structure has changed in the API

### ISSUE THREAD

**Issue by aminebenkeroum** [remixz/messenger-bot#38]
Hello everyone I'm getting this error

message: '(#100) Invalid keys "sayHi" were found in param "message".',

And I think the message structure has changed, please update your client.

**Comment by eXeDK** [comment]
The message structure has not changed as far as I know. Please provide the code that are failing. The problem may be in your own code.

**Comment by aminebenkeroum** [comment]
The problem is within "reply" function in the Skeleton code ! Now I'm using : 
`bot.sendMessage(sessions[sessionId].fbid, payload ,(err, body) => {
        if(!err)
        sessions[sessionId].context.done = true;
   });` 
And it's working just fine, yet yes there are no changes in the message structure.

Thank you

**Comment by eXeDK** [comment]
I would like to see what your payload variable contains. The "sayHi" key is not documented anywhere in the reference: https://developers.facebook.com/docs/messenger-platform/send-api-reference/text-message

**Comment by aminebenkeroum** [comment]
Heym It contains an object `{text : randomMessage } `

**Comment by eXeDK** [comment]
`
bot.on('message', messageHandler);

const messageHandler = (payload, reply) => {
  reply({'text': 'Your goal is set. Nice work Joachim.'})
}`

Should work without a problem. Which is the standard for replying to a message with a text message as defined in the reference.

**Comment by aminebenkeroum** [comment]
Actually one of my function returning random messages made base on the user's profile, is returning an object not a string. 

Works like a charm now. 

Thank you Thomas.

**Comment by eXeDK** [comment]
No problem at all, have a great day.
