### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by machineghost** [remixz/messenger-bot#41]
The Facebook documentation [here](https://developers.facebook.com/docs/graph-api/using-graph-api#errors) explains that you can get further details about your errors by providing `debug: 'all'`.  However, it does not appear possible to provide `debug: 'all'` in messenger-bot.  Could you please provide a way to set this flag when sending messages?

**Comment by remixz** [comment]
Ah, that'd be awesome to have! Great suggestion. Maybe it could be something like when you create the Bot instance, you could pass an option like:

```js
let bot = new Bot({
  token: 'PAGE_TOKEN',
  verify: 'VERIFY_TOKEN',
  app_secret: 'APP_SECRET',
  debug: 'all' // 'all', 'info', 'warning', default false
})
```

And then it'd attach the debug info to errors.

**Comment by machineghost** [comment]
Sounds good to me :)

**Comment by eXeDK** [comment]
I have started on this, just need to write some tests.
