### ISSUE TITLE
Error while conversing

### ISSUE THREAD

**Issue by aminebenkeroum** [remixz/messenger-bot#43]
Hello everyone, 

I don't know why I keep having this problem : 

` message: '(#100) No matching user found',
  type: 'OAuthException',
  code: 100,
  fbtrace_id: 'CFuhU0qaJiv' }
`
I know it's coming from Facebook API, is there any fix to that ? 

Thank you.

**Comment by dirathea** [comment]
I've got that error too :)

**Comment by massic80** [comment]
I'm having that error because "message" event is triggered also when bot replies to the user.
May these bugs be related?

**Comment by eXeDK** [comment]
@massic80 is this resolved by using 2.4.0? In 2.4.0 echos are handled separately from messages.
