### ISSUE TITLE
Non-Message Actions (eg. persistent menus and greeting text)

### ISSUE THREAD

**Issue by machineghost** [remixz/messenger-bot#45]
If you want to set a persistent menu or change the welcome greeting you need to make a non-message request:

>In order to configure the Thread Settings, make a POST call to /me/thread_settings
>access_token=PAGE_ACCESS_TOKEN with the parameters in the body. 

https://developers.facebook.com/docs/messenger-platform/thread-settings

And to configure a greeting ...

    curl -X POST -H "Content-Type: application/json" -d '{
      "setting_type":"greeting",
      "greeting":{
        "text":"Timeless apparel for the masses."
      }
    }' "https://graph.facebook.com/v2.6/me/thread_settings?access_token=PAGE_ACCESS_TOKEN"    

Is there any way to make these requests with messenger-bot, and if not is there any plan to support them in the future?

**Comment by remixz** [comment]
Just added with 2.4.0! Take a look at the README for all the docs. 😄  Thanks for your suggestion!

**Comment by machineghost** [comment]
>Thanks for your suggestion!
Thanks for implementing it!

**Comment by XavierColombel** [comment]
Sorry but I don't see anything about greeting. Help please.

**Comment by machineghost** [comment]
Sorry I stopped using this library (changed jobs) shortly after that.

**Comment by eXeDK** [comment]
@XavierColombel please see the documentation of this package and the documentation of the facebook messenger platform. I see there might be changes to the API since this functionality was implemented. You are more than welcome to commit a pull request if you change anything.
