### ISSUE TITLE
Support for multiple Facebook Pages

### ISSUE THREAD

**Issue by kzka90** [remixz/messenger-bot#47]
Hey, Is there any way to easily adapt the code so it can handle multiple Facebook Pages (Multiple Tokens) using the "same middleware" / incoming port.

Thanks in advance.

**Comment by eXeDK** [comment]
Hi Carlos,

I believe the easiest would be to start two servers on their own ports if you need to share the code for handling the messages etc. The page verification etc. do not support multiple Facebook pages at this time and I don't see a very easy fix since the bot don't really know its own page id. 

Best Regards
Thomas

**Comment by kzka90** [comment]
I managed to do it, I'll be sharing my solution soon, I need to clean it.

The page id is on the payload of the received message {payload.recipient.id}

I'm loading a middleware in one port and piping all the messages to different instances depending on the page id, I modified a little bit the messenger-bot npm so you specify the token every time you send a message (doing this so it can send messages thru the base instance)

**Comment by eXeDK** [comment]
Yeah exactly but you still need a mapping between your page id your tokens right? 

Be free to share your solution later on as you clean up your code.

**Comment by kzka90** [comment]
Yes, you can get all the access tokens and ids of your pages really easily with the Facebook API.

**Comment by eXeDK** [comment]
@kzka90 feel free to do a pull request for your progress, I'll close this issue until then.

**Comment by felippenardi** [comment]
@kzka90 Carlos, this will be very useful if you can share
