### ISSUE TITLE
Support notification_type

### ISSUE THREAD

**Issue by ahanriat** [remixz/messenger-bot#59]
Hi !

I would love to make a PR to add the support for `notification_type` [see doc](https://developers.facebook.com/docs/messenger-platform/send-api-reference#payload), but before doing that I would like to figure out the correct API. Here are some ideas, let me know what do you think:

**Proposition 1**
Wrap the current `payload`, and `notification_type` into an object.
Cons: Breaking change
```javascript
sendMessage (recipient, {payload, notification_type} , cb) {
    return request({
      method: 'POST',
      uri: 'https://graph.facebook.com/v2.6/me/messages',
      qs: this._getQs(),
      json: {
        recipient: { id: recipient },
        message: payload,
        notification_type,
      }
    })
...
```

**Proposition 2**
Add `notification_type` as another parameter. We could check the type of the third param to decide in which case we are.
Pro: no breaking change

```javascript
sendMessage (recipient, payload, notification_type , cb) {
    return request({
      method: 'POST',
      uri: 'https://graph.facebook.com/v2.6/me/messages',
      qs: this._getQs(),
      json: {
        recipient: { id: recipient },
        message: payload,
        notification_type,
      }
    })
...
```

**Proposition 3**
Wrap all params in an object. 
Cons: Breaking Change (we could check params and support the old api)
Pro: Easy to add / remove params and avoid error with params order

```javascript
sendMessage ({recipient, payload, notification_type, cb} ) {
    return request({
      method: 'POST',
      uri: 'https://graph.facebook.com/v2.6/me/messages',
      qs: this._getQs(),
      json: {
        recipient: { id: recipient },
        message: payload,
        notification_type,
      }
    })
...
```

Cheers !

**Comment by eXeDK** [comment]
Hi Antoine!

My initial thoughts are to avoid any breaking changes so Proposition 2 is to prefer from the get go I think.

I'll leave this open for a bit for others to contribute with their ideas as well. Maybe @remixz has some thoughts as well on this matter.

Best regards and merry christmast

**Comment by k-yle** [comment]
has this been implemented?
