### ISSUE TITLE
referral event handler is  not working

### ISSUE THREAD

**Issue by rabter** [remixz/messenger-bot#63]
Hi, I tried to use 'bot.on('referral', (payload, reply, actions) => {
    console.log(` ref info : ${payload.referral.ref}`)
}
then, through m.me/PAGE?ref=xxx, I entered the page messenger
but I couldn't track ref event. 

I'd like to know how to solve the problem.

**Comment by jacob-cross99** [comment]
I also have this issue.. All other event handlers work fine though.

**Comment by hemache** [comment]
**TL;DR**
install package directly from Github
`yarn add git+https://github.com/remixz/messenger-bot`
OR 
`npm install git+https://github.com/remixz/messenger-bot`

**Explanation**
for some reason, [the package in NPM](https://registry.npmjs.org/messenger-bot/-/messenger-bot-2.4.0.tgz) and YARN repositories doesn't contains latest modifications despite having identical version number `2.4.0`.   
```
// handle referrals (e.g. m.me links)
if (event.referral) {
    this._handleEvent('referral', event)
}
```

**Comment by eXeDK** [comment]
v2.5.0 are now out with this support.
