### ISSUE TITLE
Trying to get setGetStartedButton working

### ISSUE THREAD

**Issue by XavierColombel** [remixz/messenger-bot#67]
I've activated all webhooks on Facebook.

I'm trying to configure the `Get Started Button` but it's not working. Not button at all. Any idea?

```
bot.setGetStartedButton({
    "get_started":{
        "payload":"GET_STARTED_PAYLOAD"
    }
}, null);
```

**Comment by jsappme** [comment]
setGetStartedButton not working on android, here is my code:
```
bot.setGetStartedButton([{
  'payload' : 'GET_STARTED_PAYLOAD'
}])
```

**Comment by XavierColombel** [comment]
Any I switched to botly...
