### ISSUE TITLE
Does this functionality belong in the repo?

### ISSUE THREAD

**Issue by hpincket** [remixz/messenger-bot#7]
When I wrote a bot this weekend I found it useful to send messages one after the other. You cannot rely on the code order of calls to`sendMessage` because messages may arrive in different orders. Logically this requires that you wait for the `on delivery` event before you send the next message. When handling more than one conversation this requires a lookup-table to keep conversations separated.

I've added this functionality to `separateMessages` found [here](https://github.com/hpincket/messenger-bot/blob/master/separateMessages.js).

Use is as follows:
```javascript
const SeparateMessages = require('./../separateMessages')

let bot = new Bot({...})

SeparateMessages.registerBot(bot)

// Pass a list of strings, each string will be sent separately
SeparateMessages.sendSeparateMessages(payload.sender.id,
        ["It was only a sunny smile, and little it cost in the giving,", 
         "but like morning light",
         "it scattered the night and made the day worth living."],
        (err, profile) => {
                       console.log("It is done");
                     })
```

Does this functionality have a place in your repo?
I know my code doesn't follow your JS conventions, but that can be fixed.

**Comment by hpincket** [comment]
I've also added a function which allows the user to check if a given message was sent as part of a separateMessage. This is necessary if the user wants to implement their own on delivery listener, but doesn't want to handle those messages part of separateMessages which are delivered.

**Comment by maciekmm** [comment]
@hpincket 
Thanks for your contribution, but I have a few concerns:

I am not a javascript developer, but the implementation looks awful.
The main repo is kept in OOP paradigm, meaning that one can create more than one Bot instance.
As you can probably see registering multiple bot instances for your module does not work. 

Moreover, I don't see a reason to send multiple messages, maybe for aesthetic purposes?
Also I don't personally think it fits here, but that's just my personal opinion of course so feedback from other devs is appreciated.

**Comment by hpincket** [comment]
@maciekmm 
Thanks for the feedback.

As I'm sure you've picked up, I am no javascript developer myself. So I warmly welcome criticisms and suggestions. You're right, this will only work with a single bot, how short-sighted of me! Besides that, would you rather the implementation lie inside of the existing OOP Bot object? I am just trying to understand what a better implementation might look like.

Of course, if you don't see a fit in the repo, the above questions are solely for my improvement.

As far as a use case goes, I wrote a bot which needed to convey a paragraph or two of information to the user. We began with a single message approach, but it was too much. The unapproachable wall of text negated any benefit gained from a conversational UI. The other approach was have the user respond when read for the next part of the message. (Something like "Are you ready to continue?"). This felt too robotic, so we went with separate messages.

**Comment by eXeDK** [comment]
This is probably not something we want to implement at this time or with this specific API, I'll therefore close this issue. Thank you for the suggestion and effort put into this issue.
