### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by wildramen** [remixz/messenger-bot#74]
There's a error when running a simple echo test without middlware.

Error: Cannot read property 'forEach' of undefined. at (...) \node_modules\messenger-bot\index.js:188:12

**Comment by danielnjoo** [comment]
Did you find resolution to this?

**Comment by wildramen** [comment]
@danielnjoo Sorry for not replying. No, i didn't. I switched to using other Messenger Bot module.
