### ISSUE TITLE
Bot throwing undefined 'forEach' on functions without parsed.entry[0].messaging[0]

### ISSUE THREAD

**Issue by ianhayes** [remixz/messenger-bot#77]
`TypeError: Cannot read property 'forEach' of undefined` getting thrown when using 
```
let getStartedPayloads = [
  {
    payload: 'click_on_welcome_button'
  }
]

bot.setGetStartedButton(getStartedPayloads, (err) => {
  if (err) console.log( err );
})
```

The issue is from line 183 on index.js. The `_handleMessage` method was looking for `messages` but this only exists in user sent messages.

**Comment by danielnjoo** [comment]
Also interested in this.
