### ISSUE TITLE
The package in NPM is not updated

### ISSUE THREAD

**Issue by camilaavilarinho** [remixz/messenger-bot#85]
The package in NPM (version 2.4.0) is not updated with the latest modifications, see:
[Latest](https://github.com/remixz/messenger-bot/blob/master/index.js) vs [version 2.4.0](https://github.com/remixz/messenger-bot/blob/v2.4.0/index.js)

I was having a lot of trouble to work with the package till realize this.

**Comment by baudev** [comment]
Please @remixz consider doing it.
It could be annoying (as working on it this morning for nothing 😢 ).

There are important function's modifications between these two versions such as PersistentMenu, GetStartedButton or even GreetingText.

**Comment by baudev** [comment]
@remixz This issue can be closed as the `v2.5.0` is out.
