### ISSUE TITLE
Facebook Graph API 2.6v will be deprecated.

### ISSUE THREAD

**Issue by rabter** [remixz/messenger-bot#93]
I saw a message that Facebook Graph API 2.6v will be deprecated on Jul 13, 2018.
Do you have any plans for an update?

**Comment by eXeDK** [comment]
Yes I know and it is a problem for this package. 
I'm open for PRs that handle this update, I'm not sure I will have time to do it myself before the 13th of July. 

Are you up for the job @rabter ?

**Comment by rabter** [comment]
yes, I have to develop a chatbot until Aug. That’s why I need the update. Otherwise, I have to make it myself.

**Comment by eXeDK** [comment]
Feel free to create a PR, I'll review it and release an updated version on NPM together with the other changes we have gotten lately.

**Comment by eXeDK** [comment]
Have updated to 2.12, will push to NPM soon
